// src/generativeUI/adaptive-ui-architecture/components/adaptive-table/adaptive-table.component.ts
/**
 * Adaptive Table Component — Example of Truly Adaptive UI
 * 
 * This table CHANGES based on:
 * - User behavior (column preferences, sort patterns)
 * - Context (device, task mode, data characteristics)
 * - Learned preferences (page size, density)
 */

import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { contextProvider } from '../../core/context/context-provider';
import { adaptationEngine } from '../../core/adaptation/engine';
import type { AdaptationDecision } from '../../core/adaptation/types';
import type { AdaptiveContext } from '../../core/context/types';

interface TableColumn {
  id: string;
  label: string;
  sortable?: boolean;
  width?: string;
}

interface TableRow {
  [key: string]: unknown;
}

@Component({
  selector: 'adaptive-table',
  template: `
    <div class="adaptive-table" 
         [class.density-compact]="adaptation?.layout.density === 'compact'"
         [class.density-comfortable]="adaptation?.layout.density === 'comfortable'"
         [class.density-spacious]="adaptation?.layout.density === 'spacious'"
         role="table"
         [attr.aria-label]="ariaLabel"
         [attr.aria-busy]="loading">
      
      <!-- Suggested Filters (Adaptive) -->
      <div *ngIf="adaptation?.content.suggestedFilters?.length" 
           class="suggested-filters"
           role="region"
           aria-label="Suggested filters based on your usage patterns">
        <span class="suggestion-label">Quick filters:</span>
        <button *ngFor="let filter of adaptation?.content.suggestedFilters"
                class="filter-chip"
                (click)="applyFilter(filter)"
                [attr.aria-label]="'Apply filter: ' + filter.field + ' ' + filter.value">
          {{ filter.field }}: {{ filter.value }}
          <span class="filter-reason">{{ filter.reason }}</span>
        </button>
      </div>

      <!-- Table Header -->
      <div class="table-header" role="rowgroup">
        <div class="table-row" role="row">
          <div *ngFor="let col of visibleColumns; let i = index"
               class="table-cell header-cell"
               role="columnheader"
               [attr.aria-sort]="getSortDirection(col.id)"
               [style.width]="col.width"
               [class.sortable]="col.sortable"
               (click)="col.sortable && sort(col.id)"
               (keydown.enter)="col.sortable && sort(col.id)"
               (keydown.space)="col.sortable && sort(col.id)"
               [tabindex]="col.sortable ? 0 : -1">
            {{ col.label }}
            <span *ngIf="col.sortable" class="sort-indicator" aria-hidden="true">
              {{ getSortIcon(col.id) }}
            </span>
          </div>
        </div>
      </div>

      <!-- Table Body -->
      <div class="table-body" role="rowgroup">
        <div *ngFor="let row of paginatedData; let i = index"
             class="table-row"
             role="row"
             [tabindex]="0"
             (focus)="onRowFocus(i)">
          <div *ngFor="let col of visibleColumns"
               class="table-cell"
               role="cell"
               [style.width]="col.width">
            {{ row[col.id] }}
          </div>
        </div>
      </div>

      <!-- Pagination (Adaptive page size) -->
      <div class="pagination" role="navigation" aria-label="Table pagination">
        <span class="page-info">
          Showing {{ startIndex + 1 }}-{{ endIndex }} of {{ totalRows }}
        </span>
        <div class="page-controls">
          <button (click)="prevPage()" 
                  [disabled]="currentPage === 1"
                  aria-label="Previous page">
            ← Previous
          </button>
          <span class="page-number">Page {{ currentPage }} of {{ totalPages }}</span>
          <button (click)="nextPage()" 
                  [disabled]="currentPage === totalPages"
                  aria-label="Next page">
            Next →
          </button>
        </div>
        
        <!-- Page size (learned from user behavior) -->
        <select [(ngModel)]="pageSize" 
                (change)="onPageSizeChange()"
                aria-label="Rows per page">
          <option [value]="10">10 per page</option>
          <option [value]="25">25 per page</option>
          <option [value]="50">50 per page</option>
          <option [value]="100">100 per page</option>
        </select>
      </div>

      <!-- Onboarding hint (shown for novice users) -->
      <div *ngIf="adaptation?.feedback.showOnboardingHints && !hasInteracted"
           class="onboarding-hint"
           role="note">
        💡 Tip: Click column headers to sort. Your preferences will be remembered.
      </div>
    </div>
  `,
  styles: [`
    .adaptive-table {
      font-family: var(--font-family, system-ui);
    }
    .density-compact .table-cell { padding: 4px 8px; font-size: 13px; }
    .density-comfortable .table-cell { padding: 8px 16px; font-size: 14px; }
    .density-spacious .table-cell { padding: 12px 24px; font-size: 15px; }
    
    .suggested-filters {
      padding: 8px;
      background: var(--surface-secondary, #f5f5f5);
      border-radius: 4px;
      margin-bottom: 8px;
    }
    .filter-chip {
      padding: 4px 12px;
      border-radius: 16px;
      border: 1px solid var(--border-color, #ccc);
      background: white;
      cursor: pointer;
      margin: 0 4px;
    }
    .filter-chip:hover { background: var(--hover-bg, #eee); }
    .filter-chip:focus-visible {
      outline: 2px solid var(--focus-color, #0066cc);
      outline-offset: 2px;
    }
    .filter-reason {
      font-size: 11px;
      color: var(--text-secondary, #666);
      margin-left: 4px;
    }
    
    .table-row:focus-visible {
      outline: 2px solid var(--focus-color, #0066cc);
      outline-offset: -2px;
    }
    .header-cell.sortable { cursor: pointer; }
    .header-cell.sortable:hover { background: var(--hover-bg, #eee); }
    
    .onboarding-hint {
      padding: 12px;
      background: var(--info-bg, #e3f2fd);
      border-radius: 4px;
      margin-top: 8px;
      font-size: 13px;
    }
  `]
})
export class AdaptiveTableComponent implements OnInit, OnDestroy {
  @Input() columns: TableColumn[] = [];
  @Input() data: TableRow[] = [];
  @Input() ariaLabel = 'Data table';
  
  adaptation: AdaptationDecision | null = null;
  loading = false;
  hasInteracted = false;
  // ... additional properties would continue
}

// src/generativeUI/adaptive-ui-architecture/components/react/AdaptiveTable.tsx
/**
 * Adaptive Table — React Component
 * 
 * A table that adapts to user behavior, context, and preferences.
 * 
 * Features:
 * - Learns column preferences from user behavior
 * - Adapts density based on device/preference
 * - Shows suggested filters from capture patterns
 * - Accessible with WCAG AA compliance
 */

import React, { useState, useMemo, useCallback, useEffect } from 'react';
import { useAdaptation, useAdaptiveLayout } from '../../core/adaptation/react/use-adaptation';
import { createCaptureHooks } from '../../core/capture/capture-service';
import './AdaptiveTable.css';

// ============================================================================
// TYPES
// ============================================================================

export interface Column {
  id: string;
  label: string;
  sortable?: boolean;
  width?: string;
  align?: 'left' | 'center' | 'right';
}

export interface AdaptiveTableProps {
  columns: Column[];
  data: Record<string, unknown>[];
  tableId: string;
  ariaLabel?: string;
  onSort?: (columnId: string, direction: 'asc' | 'desc') => void;
  onFilter?: (field: string, value: unknown) => void;
  onRowSelect?: (row: Record<string, unknown>, index: number) => void;
}

// ============================================================================
// COMPONENT
// ============================================================================

export function AdaptiveTable({
  columns,
  data,
  tableId,
  ariaLabel = 'Data table',
  onSort,
  onFilter,
  onRowSelect,
}: AdaptiveTableProps) {
  const { content, interaction, confidence } = useAdaptation();
  const { spacing, densityClass } = useAdaptiveLayout();
  
  // Capture hooks for learning
  const capture = useMemo(
    () => createCaptureHooks({ componentType: 'table', componentId: tableId }),
    [tableId]
  );
  
  // State
  const [sortColumn, setSortColumn] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
  const [currentPage, setCurrentPage] = useState(1);
  const [hasInteracted, setHasInteracted] = useState(false);
  
  // Adaptive page size from learned preferences
  const pageSize = content.pageSize || 25;
  
  // Column visibility from learned preferences
  const visibleColumns = useMemo(() => {
    if (content.visibleColumns?.length > 0) {
      return columns.filter(col => content.visibleColumns.includes(col.id));
    }
    return columns;
  }, [columns, content.visibleColumns]);
  
  // Column order from learned preferences
  const orderedColumns = useMemo(() => {
    if (content.columnOrder?.length > 0) {
      return [...visibleColumns].sort((a, b) => {
        const aIndex = content.columnOrder.indexOf(a.id);
        const bIndex = content.columnOrder.indexOf(b.id);
        if (aIndex === -1) return 1;
        if (bIndex === -1) return -1;
        return aIndex - bIndex;
      });
    }
    return visibleColumns;
  }, [visibleColumns, content.columnOrder]);
  
  // Sorting
  const handleSort = useCallback((columnId: string) => {
    setHasInteracted(true);
    const newDirection = sortColumn === columnId && sortDirection === 'asc' ? 'desc' : 'asc';
    setSortColumn(columnId);
    setSortDirection(newDirection);
    
    // Capture for learning
    capture.captureSort(columnId, newDirection);
    onSort?.(columnId, newDirection);
  }, [sortColumn, sortDirection, capture, onSort]);
  
  // Pagination
  const totalPages = Math.ceil(data.length / pageSize);
  const paginatedData = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return data.slice(start, start + pageSize);
  }, [data, currentPage, pageSize]);
  
  // Filter chips from learned patterns
  const suggestedFilters = content.suggestedFilters || [];
  
  const handleFilterClick = useCallback((filter: { field: string; value: unknown }) => {
    capture.captureFilter(filter.field, filter.value);
    onFilter?.(filter.field, filter.value);
  }, [capture, onFilter]);
  
  // Row selection
  const handleRowClick = useCallback((row: Record<string, unknown>, index: number) => {
    capture.captureClick(`row-${index}`);
    onRowSelect?.(row, index);
  }, [capture, onRowSelect]);

  // Keyboard navigation
  const handleKeyDown = useCallback((
    e: React.KeyboardEvent,
    rowIndex: number
  ) => {
    if (e.key === 'ArrowDown' && rowIndex < paginatedData.length - 1) {
      e.preventDefault();
      const nextRow = document.querySelector(
        `[data-row-index="${rowIndex + 1}"]`
      ) as HTMLElement;
      nextRow?.focus();
    } else if (e.key === 'ArrowUp' && rowIndex > 0) {
      e.preventDefault();
      const prevRow = document.querySelector(
        `[data-row-index="${rowIndex - 1}"]`
      ) as HTMLElement;
      prevRow?.focus();
    }
  }, [paginatedData.length]);

  return (
    <div 
      className={`adaptive-table ${densityClass}`}
      style={{ '--spacing': `${spacing}px` } as React.CSSProperties}
    >
      {/* Suggested Filters */}
      {suggestedFilters.length > 0 && confidence > 0.3 && (
        <div className="suggested-filters" role="region" aria-label="Quick filters">
          <span className="filter-label">Quick filters:</span>
          {suggestedFilters.map((filter, i) => (
            <button
              key={i}
              className="filter-chip"
              onClick={() => handleFilterClick(filter)}
              aria-label={`Filter by ${filter.field}: ${filter.value}`}
            >
              {filter.field}: {String(filter.value)}
              {filter.reason && (
                <span className="filter-reason">{filter.reason}</span>
              )}
            </button>
          ))}
        </div>
      )}

      {/* Table */}
      <table role="table" aria-label={ariaLabel}>
        <thead>
          <tr>
            {orderedColumns.map(col => (
              <th
                key={col.id}
                scope="col"
                style={{ width: col.width, textAlign: col.align || 'left' }}
                className={col.sortable ? 'sortable' : ''}
                aria-sort={
                  sortColumn === col.id
                    ? sortDirection === 'asc' ? 'ascending' : 'descending'
                    : undefined
                }
                onClick={() => col.sortable && handleSort(col.id)}
                onKeyDown={(e) => {
                  if (col.sortable && (e.key === 'Enter' || e.key === ' ')) {
                    e.preventDefault();
                    handleSort(col.id);
                  }
                }}
                tabIndex={col.sortable ? 0 : -1}
              >
                {col.label}
                {col.sortable && sortColumn === col.id && (
                  <span className="sort-indicator" aria-hidden="true">
                    {sortDirection === 'asc' ? ' ↑' : ' ↓'}
                  </span>
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {paginatedData.map((row, rowIndex) => (
            <tr
              key={rowIndex}
              data-row-index={rowIndex}
              tabIndex={0}
              onClick={() => handleRowClick(row, rowIndex)}
              onKeyDown={(e) => handleKeyDown(e, rowIndex)}
              className="table-row"
            >
              {orderedColumns.map(col => (
                <td
                  key={col.id}
                  style={{ textAlign: col.align || 'left' }}
                >
                  {String(row[col.id] ?? '')}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      {/* Pagination */}
      <nav className="pagination" aria-label="Table pagination">
        <span className="page-info">
          {(currentPage - 1) * pageSize + 1}–{Math.min(currentPage * pageSize, data.length)} of {data.length}
        </span>
        <div className="page-controls">
          <button
            onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
            disabled={currentPage === 1}
            aria-label="Previous page"
          >
            ← Prev
          </button>
          <span className="page-number">
            Page {currentPage} of {totalPages}
          </span>
          <button
            onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
            disabled={currentPage === totalPages}
            aria-label="Next page"
          >
            Next →
          </button>
        </div>
      </nav>

      {/* Onboarding hint for low-confidence users */}
      {!hasInteracted && confidence < 0.3 && (
        <div className="onboarding-hint" role="note">
          💡 Tip: Click column headers to sort. Your preferences will be remembered.
        </div>
      )}
    </div>
  );
}
